"""added language to Post

Revision ID: 33225802bb5b
Revises: eb56c2b1b56c
Create Date: 2019-02-24 15:22:22.291230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33225802bb5b'
down_revision = 'eb56c2b1b56c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
